#!/bin/bash
#dunstVolIndicator

# Query pavu for the current volume and whether or not the speaker is muted
volume="$(pactl get-sink-volume 0 | cut -d'/' -f 2 | cut -c2-4 | sed 's/ //g')"
mute="$(pactl get-sink-mute 0 | cut -d':' -f 2 | sed 's/ //g')"
if [[ $volume == 0 || "$mute" == "yes" ]]; then
    # Show the sound muted notification
    dunstify -a "changeVolume" -u low -r 98245 -h string:x-dunst-stack-tag:$msgTag "Volume muted"
else
    # Show the volume notification
    dunstify -a "changeVolume" -u low -i audio-volume-high -r 98245 -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$volume" "Volume: ${volume}%"
fi

# Play the volume changed sound
#canberra-gtk-play -i audio-volume-change -d "changeVolume"
